# Generated by Django 3.2.11 on 2022-08-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите язык на котором вы хотите посмотреть новости', max_length=20, verbose_name='Язык новостей')),
            ],
        ),
        migrations.CreateModel(
            name='Novosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тему новостей', max_length=200, verbose_name='Тема новостей')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тип документа', max_length=200, verbose_name='Тип документа')),
                ('summary', models.TextField(help_text='Введите краткое описание документа', max_length=1000, verbose_name='Аннотация документа')),
                ('language', models.ForeignKey(help_text='Выберите язык для просмотра документа', null=True, on_delete=django.db.models.deletion.CASCADE, to='News.language', verbose_name='Язык докумета')),
            ],
        ),
    ]
